import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  mySidebar: [
    {
      type: 'category',
      label: 'Photoshop',
      description: 'this is so wrong',
      collapsible: true, // Set the category to be collapsible
      collapsed: true, // Set the category to be initially collapsed or open by default
      link: {
        type: 'generated-index',
        title: 'Photoshop Guides',
        description: 'Learn about photoshop concepts!',
        slug: '/category/photoshop-guides',
        keywords: ['photoshop'],
        image: '/img/undraw_docusaurus_react.svg',
      },
      items: [
        {
          type: 'doc',
          id: 'photoshop/index',
          label: '- Photoshop',
        },
      ],
    },
    {
      type: 'category',
      label: 'Programming',
      collapsible: true, // Set the category to be collapsible
      collapsed: false, // Set the category to be initially collapsed or open by default
      link: {
        type: 'generated-index',
        title: 'Programming Guides',
        description: 'All the information a developer needs',
        slug: '/programming', // defaults to: '/category/[categoryName]'
        keywords: ['programming', 'git', 'css', 'ssh', 'docker', 'helm', 'node', 'nestjs'],
        image: '/img/undraw_docusaurus_react.svg',
      },
      items: [
        {
          type: 'doc',
          id: 'programming/aws-kubernetes',
          label: '- AWS Kubernetes',
        },
        {
          type: 'doc',
          id: 'programming/certificates',
          label: '- Certificates',
        },
        {
          type: 'doc',
          id: 'programming/crypto',
          label: '- Crypto',
        },
        {
          type: 'doc',
          id: 'programming/css',
          label: '- CSS',
        },
        {
          type: 'category',
          label: '- Databases',
          link: {
            type: 'generated-index',
            title: 'Databases Guides',
            description: 'All about databases',
            slug: '/db',
            keywords: ['database'],
          },
          items: [
            {
              type: 'doc',
              id: 'programming/databases/elasticsearch',
              label: '- ElasticSearch',
            },
            {
              type: 'doc',
              id: 'programming/databases/indexed-db',
              label: '- IndexedDB',
            },
            {
              type: 'doc',
              id: 'programming/databases/mongodb',
              label: '- MongoDB',
            },
            {
              type: 'doc',
              id: 'programming/databases/postgres-sql',
              label: '- Postgres',
            },
            {
              type: 'doc',
              id: 'programming/databases/redis',
              label: '- Redis',
            },
          ],
        },
        {
          type: 'category',
          label: '- DevOps',
          link: {
            type: 'generated-index',
            title: 'DevOps Guides',
            description: 'All about DevOps',
            slug: '/devops',
            keywords: ['devops'],
          },
          items: [
            {
              type: 'category',
              label: '- Docker',
              link: {
                type: 'generated-index',
                title: 'Docker Guides',
                description: 'All about Docker',
                slug: '/docker',
                keywords: ['docker'],
              },
              items: [
                {
                  type: 'doc',
                  id: 'programming/devops/docker/most-useful-commands',
                  label: '- Most Useful Commands',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/docker/docker-commands',
                  label: '- All Docker Commands',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/docker/how-to-create-a-dockerfile',
                  label: '- How to Create a Dockerfile',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/docker/avoiding-architecture-mismatch',
                  label: '- Avoiding Architecture Mismatch',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/docker/docker-compose-commands',
                  label: '- Docker Compose Commands',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/docker/how-to-create-a-docker-compose-file',
                  label: '- How to Create a Docker-Compose File',
                },
              ],
            },
            {
              type: 'category',
              label: '- Kubernetes',
              link: {
                type: 'generated-index',
                title: 'Kubernetes Guides',
                description: 'All about Kubernetes',
                slug: '/kubernetes',
                keywords: ['kubernetes'],
              },
              items: [
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/overview',
                  label: '- Overview',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/most-useful-commands',
                  label: '- Most Useful Commands',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/kubectl-commands',
                  label: '- All Kubectl Commands',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/resources',
                  label: '- Resources',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/kubernetes-api-server',
                  label: '- kube-apiserver',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/architecture-and-concepts',
                  label: '- Architecture and Concepts',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/kubernetes-rbac',
                  label: '- RBAC',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/troubleshooting',
                  label: '- Troubleshooting',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/minikube',
                  label: '- Minikube',
                },
              ],
            },
            {
              type: 'doc',
              id: 'programming/devops/helm',
              label: '- Helm',
            },
          ],
        },
        {
          type: 'doc',
          id: 'programming/design-patterns',
          label: '- Design Patterns',
        },
        {
          type: 'doc',
          id: 'programming/elk',
          label: '- ELK Stack',
        },
        {
          type: 'doc',
          id: 'programming/git',
          label: '- Git',
        },
        {
          type: 'category',
          label: '- Javascript',
          link: {
            type: 'generated-index',
            title: 'JavaScript Guides',
            description: 'Advanced concepts of JavaScript',
            slug: '/js',
            keywords: ['javascript'],
          },
          items: [
            {
              type: 'doc',
              id: 'programming/javascript/call-apply-bind',
              label: '- Call, Apply & Bind',
            },
            {
              type: 'doc',
              id: 'programming/javascript/iterator',
              label: '- Iterator',
            },
            {
              type: 'doc',
              id: 'programming/javascript/getters-and-setters',
              label: '- Getters & Setters',
            },
            {
              type: 'doc',
              id: 'programming/javascript/strict-mode',
              label: '- Strict Mode',
            },
            {
              type: 'doc',
              id: 'programming/javascript/prototype',
              label: '- Prototype',
            },
            {
              type: 'doc',
              id: 'programming/javascript/valueOf',
              label: '- valueOf',
            },
            {
              type: 'doc',
              id: 'programming/javascript/finalization-registry',
              label: '- FinalizationRegistry',
            },
          ],
        },
        {
          type: 'doc',
          id: 'programming/micro-frontends',
          label: '- Micro-Frontends',
        },
        {
          type: 'doc',
          id: 'programming/nest',
          label: '- NestJS',
        },
        {
          type: 'doc',
          id: 'programming/node',
          label: '- Node',
        },
        {
          type: 'doc',
          id: 'programming/npm',
          label: '- Npm publish a package',
        },
        {
          type: 'doc',
          id: 'programming/python-server',
          label: '- Python Server',
        },
        {
          type: 'doc',
          id: 'programming/regex',
          label: '- Regex',
        },
        {
          type: 'doc',
          id: 'programming/saml',
          label: '- SAML',
        },
        {
          type: 'category',
          label: '- Javascript',
          link: {
            type: 'generated-index',
            title: 'JavaScript Guides',
            description: 'Advanced concepts of JavaScript',
            slug: '/js',
            keywords: ['javascript'],
          },
          items: [
            {
              type: 'doc',
              id: 'programming/javascript/call-apply-bind',
              label: '- Call, Apply & Bind',
            },
            {
              type: 'doc',
              id: 'programming/javascript/iterator',
              label: '- Iterator',
            },
            {
              type: 'doc',
              id: 'programming/javascript/getters-and-setters',
              label: '- Getters & Setters',
            },
            {
              type: 'doc',
              id: 'programming/javascript/strict-mode',
              label: '- Strict Mode',
            },
            {
              type: 'doc',
              id: 'programming/javascript/prototype',
              label: '- Prototype',
            },
            {
              type: 'doc',
              id: 'programming/javascript/valueOf',
              label: '- valueOf',
            },
            {
              type: 'doc',
              id: 'programming/javascript/finalization-registry',
              label: '- FinalizationRegistry',
            },
          ],
        },
        {
          type: 'category',
          label: '- Socket IO',
          link: {
            type: 'generated-index',
            title: 'Socket IO Guides',
            description: 'Socket IO concepts',
            slug: '/socket-io',
            keywords: ['websocket', 'socketio'],
            image: '/img/heart.svg',
          },
          items: [
            {
              type: 'doc',
              id: 'programming/socket-io/getting-started',
              label: '- Getting Started',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/reserved-event-names',
              label: '- Reserved Event Names',
            },
          ],
        },
        {
          type: 'category',
          label: '- Software Concepts',
          link: {
            type: 'generated-index',
            title: 'Software Concepts Guides',
            description: 'Software development concepts',
            slug: '/software-concepts', // defaults to: '/category/[categoryName]'
            keywords: ['software'],
            image: '/img/heart.svg',
          },
          items: [
            {
              type: 'doc',
              id: 'programming/concepts/solid',
              label: '-- SOLID',
            },
            {
              type: 'doc',
              id: 'programming/concepts/design-by-contract',
              label: '-- Design By Contract',
            },
          ],
        },
        {
          type: 'doc',
          id: 'programming/software-architecture',
          label: '- Software Architecture',
        },
        {
          type: 'doc',
          id: 'programming/ssh',
          label: '- SSH',
        },
        {
          type: 'doc',
          id: 'programming/storybook',
          label: '- Storybook',
        },
        {
          type: 'doc',
          id: 'programming/syntax-highlighting',
          label: '- Syntax Highlighting',
        },
        {
          type: 'category',
          label: '- Terminal God',
          items: [
            {
              type: 'doc',
              id: 'programming/terminal-god/terminal-god',
              label: '- Terminal God',
            },
            {
              type: 'doc',
              id: 'programming/terminal-god/vi',
              label: '- VI',
            },
          ],
        },
        {
          type: 'category',
          label: '- Tests',
          link: {
            type: 'generated-index',
            title: 'Testing Frameworks',
            description: 'Testing Frameworks Tutorials',
            slug: '/tests',
            keywords: ['tests'],
          },
          items: [
            {
              type: 'doc',
              id: 'programming/tests/jest',
              label: '- Jest',
            },
            {
              type: 'doc',
              id: 'programming/tests/react-testing-library',
              label: '- React Testing Library',
            },
          ],
        },
        {
          type: 'doc',
          id: 'programming/typescript',
          label: '- TypeScript',
        },
        {
          type: 'category',
          label: '- Web',
          link: {
            type: 'generated-index',
            title: 'Web Guides',
            description: 'Advanced concepts of the web',
            slug: '/web',
            keywords: ['web'],
            image: '/img/heart.svg',
          },
          items: [
            {
              type: 'doc',
              id: 'programming/web/fetch',
              label: '- Fetch API',
            },
            {
              type: 'doc',
              id: 'programming/web/headers',
              label: '- Headers',
            },
            {
              type: 'doc',
              id: 'programming/web/history',
              label: '- History',
            },
            {
              type: 'category',
              label: '- Http',
              link: {
                type: 'generated-index',
                title: 'Http Guides',
                description: 'Advanced concepts of Http',
                slug: '/http',
                keywords: ['http'],
              },
              items: [
                {
                  type: 'doc',
                  id: 'programming/web/http/overview',
                  label: '- Http Overview',
                },
                {
                  type: 'doc',
                  id: 'programming/web/http/http-messages',
                  label: '- Http Messages',
                },
                {
                  type: 'doc',
                  id: 'programming/web/http/http1-limitations-and-http2',
                  label: '- Http/1 Limitations & Http/2',
                },
                {
                  type: 'doc',
                  id: 'programming/web/http/mime-type',
                  label: '- MIME types',
                },
              ],
            },
            {
              type: 'doc',
              id: 'programming/web/iframe',
              label: '- Iframe',
            },
            {
              type: 'doc',
              id: 'programming/web/inert',
              label: '- Inert',
            },
            {
              type: 'doc',
              id: 'programming/web/service-worker',
              label: '- Service Worker',
            },
            {
              type: 'doc',
              id: 'programming/web/web-worker',
              label: '- Web Worker',
            },
            {
              type: 'doc',
              id: 'programming/web/window',
              label: '- Window',
            },
          ],
        },
        {
          type: 'doc',
          id: 'programming/what-is-long-polling',
          label: '- What is Long-Polling',
        },
      ],
    },
    {
      type: 'category',
      label: 'Video Editing',
      items: [
        {
          type: 'doc',
          id: 'video-editing/ffmpeg',
          label: '- FFmpeg',
        },
        {
          type: 'doc',
          id: 'video-editing/subtitles-encoding',
          label: '- Subs Encoding',
        },
      ],
    },
    {
      type: 'category',
      label: 'MISC',
      items: [
        {
          type: 'doc',
          id: 'job-interview',
          label: '- Job Interview',
        },
      ],
    },
  ],
};

export default sidebars;
