import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  mySidebar: [
    {
      type: 'category',
      label: 'Knowledge Base',
      description: 'Things I will surely forget',
      collapsible: true, // Set the category to be collapsible
      collapsed: true, // Set the category to be initially collapsed or open by default
      link: {
        type: 'generated-index',
        title: 'Knowledge Base',
        description: 'Things to remember',
        slug: '/category/knowledge-base',
        keywords: ['knowledge'],
        image: '/img/undraw_docusaurus_react.svg',
      },
      items: [
        // {
        //   type: 'doc',
        //   id: 'knowledge/my-background',
        // },
        {
          type: 'doc',
          id: 'knowledge/csrf-attack',
        },
        {
          type: 'doc',
          id: 'knowledge/design-by-contract',
          label: '-- Design By Contract',
        },
        {
          type: 'doc',
          id: 'knowledge/design-patterns',
          label: '- Design Patterns',
        },
        {
          type: 'doc',
          id: 'knowledge/offset-and-cursor-based-pagination',
        },
        {
          type: 'doc',
          id: 'knowledge/post-vs-get-login',
        },
        {
          type: 'doc',
          id: 'knowledge/solid',
          label: '-- SOLID',
        },
      ],
    },
    {
      type: 'category',
      label: 'Programming',
      collapsible: true, // Set the category to be collapsible
      collapsed: false, // Set the category to be initially collapsed or open by default
      link: {
        type: 'generated-index',
        title: 'Programming Guides',
        description: 'All the information a developer needs',
        slug: '/programming', // defaults to: '/category/[categoryName]'
        keywords: ['programming', 'git', 'css', 'ssh', 'docker', 'helm', 'node', 'nestjs'],
        image: '/img/undraw_docusaurus_react.svg',
      },
      items: [
        {
          type: 'doc',
          id: 'programming/aws-kubernetes',
          label: '- AWS Kubernetes',
        },
        {
          type: 'doc',
          id: 'programming/certificates',
          label: '- Certificates',
        },
        {
          type: 'doc',
          id: 'programming/crypto',
          label: '- Crypto',
        },
        {
          type: 'doc',
          id: 'programming/css',
          label: '- CSS',
        },
        {
          type: 'category',
          label: '- Databases',
          link: {
            type: 'generated-index',
            title: 'Databases Guides',
            description: 'All about databases',
            slug: '/db',
            keywords: ['database'],
          },
          items: [
            {
              type: 'doc',
              id: 'programming/databases/elasticsearch',
              label: '- ElasticSearch',
            },
            {
              type: 'doc',
              id: 'programming/databases/indexed-db',
              label: '- IndexedDB',
            },
            {
              type: 'doc',
              id: 'programming/databases/mongodb',
              label: '- MongoDB',
            },
            {
              type: 'doc',
              id: 'programming/databases/postgres-sql',
              label: '- Postgres',
            },
            {
              type: 'doc',
              id: 'programming/databases/redis',
              label: '- Redis',
            },
          ],
        },
        {
          type: 'category',
          label: '- DevOps',
          link: {
            type: 'generated-index',
            title: 'DevOps Guides',
            description: 'All about DevOps',
            slug: '/devops',
            keywords: ['devops'],
          },
          items: [
            {
              type: 'category',
              label: '- Docker',
              link: {
                type: 'generated-index',
                title: 'Docker Guides',
                description: 'All about Docker',
                slug: '/docker',
                keywords: ['docker'],
              },
              items: [
                {
                  type: 'doc',
                  id: 'programming/devops/docker/most-useful-commands',
                  label: '- Most Useful Commands',
                  key: 'docker-most-useful-commands',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/docker/docker-commands',
                  label: '- All Docker Commands',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/docker/how-to-create-a-dockerfile',
                  label: '- How to Create a Dockerfile',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/docker/avoiding-architecture-mismatch',
                  label: '- Avoiding Architecture Mismatch',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/docker/docker-compose-commands',
                  label: '- Docker Compose Commands',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/docker/how-to-create-a-docker-compose-file',
                  label: '- How to Create a Docker-Compose File',
                },
              ],
            },
            {
              type: 'category',
              label: '- Kubernetes',
              link: {
                type: 'generated-index',
                title: 'Kubernetes Guides',
                description: 'All about Kubernetes',
                slug: '/kubernetes',
                keywords: ['kubernetes'],
              },
              items: [
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/overview',
                  label: '- Overview',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/most-useful-commands',
                  label: '- Most Useful Commands',
                  key: 'kubernetes-most-useful-commands',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/kubectl-commands',
                  label: '- All Kubectl Commands',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/resources',
                  label: '- Resources',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/kubernetes-api-server',
                  label: '- kube-apiserver',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/architecture-and-concepts',
                  label: '- Architecture and Concepts',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/kubernetes-rbac',
                  label: '- RBAC',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/troubleshooting',
                  label: '- Troubleshooting',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/kubernetes/minikube',
                  label: '- Minikube',
                },
              ],
            },
            {
              type: 'category',
              label: '- Helm',
              link: {
                type: 'generated-index',
                title: 'Kubernetes Guides',
                description: 'All about Helm',
                slug: '/helm',
                keywords: ['helm'],
              },
              items: [
                {
                  type: 'doc',
                  id: 'programming/devops/helm/introduction',
                  label: '- Introduction',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/helm/helm-architecture-and-concepts',
                  label: '- Architecture & Concepts',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/helm/helm-install-deep-dive',
                  label: '- Helm Install: Deep Dive',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/helm/helm-upgrade-deep-dive',
                  label: '- Helm Upgrade: Deep Dive',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/helm/maintain-a-chart',
                  label: '- Maintain a Chart',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/helm/helm-strategies',
                  label: '- Helm Strategies',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/helm/daily-workflow',
                  label: '- Daily Workflow',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/helm/helm-commands',
                  label: '- All helm Commands',
                },
              ],
            },
            {
              type: 'category',
              label: '- CircleCI',
              link: {
                type: 'generated-index',
                title: 'Kubernetes Guides',
                description: 'All about CircleCI',
                slug: '/circleci',
                keywords: ['circleci'],
              },
              items: [
                {
                  type: 'doc',
                  id: 'programming/devops/circleci/benefits-of-circleci',
                  label: '- Benefits of CircleCI',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/circleci/getting-started',
                  label: '- Getting Started',
                  key: 'circleci-getting-started',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/circleci/using-contexts',
                  label: '- Using Contexts',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/circleci/data-persistence',
                  label: '- Data Persistence',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/circleci/dynamic-configuration',
                  label: '- Dynamic Configuration',
                },
              ],
            },
            {
              type: 'category',
              label: '- Prometheus',
              link: {
                type: 'generated-index',
                title: 'Kubernetes Guides',
                description: 'All about Prometheus',
                slug: '/prometheus',
                keywords: ['prometheus'],
              },
              items: [
                {
                  type: 'doc',
                  id: 'programming/devops/prometheus/getting-started',
                  label: '- Getting Started',
                  key: 'prometheus-getting-started',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/prometheus/named-volume',
                  label: '- Named Volume',
                  key: 'prometheus-named-volume',
                },
                {
                  type: 'doc',
                  id: 'programming/devops/prometheus/custom-configuration',
                  label: '- Custom Configuration',
                  key: 'prometheus-custom-configuration',
                },
              ],
            },
          ],
        },
        {
          type: 'doc',
          id: 'programming/elk',
          label: '- ELK Stack',
        },
        {
          type: 'category',
          label: '- Git',
          link: {
            type: 'generated-index',
            title: 'Git Guides',
            description: 'Advanced concepts of Git',
            slug: '/git',
            keywords: ['git'],
          },
          items: [
            {
              type: 'doc',
              id: 'programming/git/git',
            },
            {
              type: 'doc',
              id: 'programming/git/git-split-diffs',
            },
            {
              type: 'doc',
              id: 'programming/git/lazy-git',
            },
          ],
        },
        {
          type: 'category',
          label: '- Javascript',
          link: {
            type: 'generated-index',
            title: 'JavaScript Guides',
            description: 'Advanced concepts of JavaScript',
            slug: '/js',
            keywords: ['javascript'],
          },
          items: [
            {
              type: 'doc',
              id: 'programming/javascript/call-apply-bind',
              label: '- Call, Apply & Bind',
            },
            {
              type: 'doc',
              id: 'programming/javascript/iterator',
              label: '- Iterator',
            },
            {
              type: 'doc',
              id: 'programming/javascript/getters-and-setters',
              label: '- Getters & Setters',
            },
            {
              type: 'doc',
              id: 'programming/javascript/strict-mode',
              label: '- Strict Mode',
            },
            {
              type: 'doc',
              id: 'programming/javascript/prototype',
              label: '- Prototype',
            },
            {
              type: 'doc',
              id: 'programming/javascript/valueOf',
              label: '- valueOf',
            },
            {
              type: 'doc',
              id: 'programming/javascript/finalization-registry',
              label: '- FinalizationRegistry',
            },
          ],
        },
        {
          type: 'doc',
          id: 'programming/micro-frontends',
          label: '- Micro-Frontends',
        },
        {
          type: 'doc',
          id: 'programming/nest',
          label: '- NestJS',
        },
        {
          type: 'doc',
          id: 'programming/node',
          label: '- Node',
        },
        {
          type: 'doc',
          id: 'programming/npm',
          label: '- Npm publish a package',
        },
        {
          type: 'doc',
          id: 'programming/python-server',
          label: '- Python Server',
        },
        {
          type: 'doc',
          id: 'programming/regex',
          label: '- Regex',
        },
        {
          type: 'doc',
          id: 'programming/saml',
          label: '- SAML',
        },
        {
          type: 'category',
          label: '- Socket IO',
          link: {
            type: 'generated-index',
            title: 'Socket IO Guides',
            description: 'Socket IO concepts',
            slug: '/socket-io',
            keywords: ['websocket', 'socketio'],
            image: '/img/heart.svg',
          },
          items: [
            {
              type: 'doc',
              id: 'programming/socket-io/getting-started',
              label: '- Getting Started',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/broadcasting',
              label: '- Broadcasting',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/acknowledgements',
              label: '- Acknowledgements',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/handle-disconnects',
              label: '- Handle Disconnects',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/connection-state-recovery',
              label: '- Connection State Recovery',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/rooms',
              label: '- Rooms',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/scaling-horizontally',
              label: '- Scaling Horizontally',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/socketio-vs-websockets',
              label: '- SocketIO vs WebSockets',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/under-the-hood-engine-io',
              label: '- Under the Hood - Engine.IO',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/under-the-hood-socket-io',
              label: '- Under the Hood - Socket.IO',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/delivery-guarantees',
              label: '- Delivery Guarantees',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/reserved-event-names',
              label: '- Reserved Event Names',
            },
            {
              type: 'doc',
              id: 'programming/socket-io/q-n-a',
              label: '- Q & A',
            },
          ],
        },
        {
          type: 'doc',
          id: 'programming/software-architecture',
          label: '- Software Architecture',
        },
        {
          type: 'doc',
          id: 'programming/ssh',
          label: '- SSH',
        },
        {
          type: 'doc',
          id: 'programming/storybook',
          label: '- Storybook',
        },
        {
          type: 'doc',
          id: 'programming/syntax-highlighting',
          label: '- Syntax Highlighting',
        },
        {
          type: 'category',
          label: '- Terminal God',
          items: [
            {
              type: 'doc',
              id: 'programming/terminal-god/linux-install',
              label: '- Linux Install',
            },
            {
              type: 'doc',
              id: 'programming/terminal-god/terminal-god',
              label: '- Terminal God',
            },
            {
              type: 'doc',
              id: 'programming/terminal-god/vi',
              label: '- VI',
            },
            {
              type: 'doc',
              id: 'programming/terminal-god/find',
              label: '- Find',
            },
            {
              type: 'doc',
              id: 'programming/terminal-god/scp',
              label: '- Scp',
            },
            {
              type: 'doc',
              id: 'programming/terminal-god/debug-a-running-node-server',
              label: '- Debug Node server',
            },
          ],
        },
        {
          type: 'category',
          label: '- Tests',
          link: {
            type: 'generated-index',
            title: 'Testing Frameworks',
            description: 'Testing Frameworks Tutorials',
            slug: '/tests',
            keywords: ['tests'],
          },
          items: [
            {
              type: 'doc',
              id: 'programming/tests/jest',
              label: '- Jest',
            },
            {
              type: 'doc',
              id: 'programming/tests/react-testing-library',
              label: '- React Testing Library',
            },
          ],
        },
        {
          type: 'doc',
          id: 'programming/typescript',
          label: '- TypeScript',
        },
        {
          type: 'category',
          label: '- Web',
          link: {
            type: 'generated-index',
            title: 'Web Guides',
            description: 'Advanced concepts of the web',
            slug: '/web',
            keywords: ['web'],
            image: '/img/heart.svg',
          },
          items: [
            {
              type: 'doc',
              id: 'programming/web/fetch',
              label: '- Fetch API',
            },
            {
              type: 'doc',
              id: 'programming/web/history',
              label: '- History',
            },
            {
              type: 'category',
              label: '- Http',
              link: {
                type: 'generated-index',
                title: 'Http Guides',
                description: 'Advanced concepts of Http',
                slug: '/http',
                keywords: ['http'],
              },
              items: [
                {
                  type: 'doc',
                  id: 'programming/web/http/overview',
                  label: '- Http Overview',
                },
                {
                  type: 'doc',
                  id: 'programming/web/http/http-messages',
                  label: '- Http Messages',
                },
                {
                  type: 'doc',
                  id: 'programming/web/http/http1-limitations-and-http2',
                  label: '- Http/1 Limitations & Http/2',
                },
                {
                  type: 'doc',
                  id: 'programming/web/http/mime-type',
                  label: '- MIME types',
                },
                {
                  type: 'doc',
                  id: 'programming/web/http/cache-control-headers',
                  label: '- Cache Control Headers',
                  key: 'cache-control-headers',
                },
              ],
            },
            {
              type: 'doc',
              id: 'programming/web/iframe',
              label: '- Iframe',
            },
            {
              type: 'doc',
              id: 'programming/web/inert',
              label: '- Inert',
            },
            {
              type: 'doc',
              id: 'programming/web/service-worker',
              label: '- Service Worker',
            },
            {
              type: 'doc',
              id: 'programming/web/web-worker',
              label: '- Web Worker',
            },
            {
              type: 'doc',
              id: 'programming/web/window',
              label: '- Window',
            },
          ],
        },
        {
          type: 'doc',
          id: 'programming/what-is-long-polling',
          label: '- What is Long-Polling',
        },
      ],
    },
    {
      type: 'category',
      label: 'Video Editing',
      items: [
        {
          type: 'doc',
          id: 'video-editing/ffmpeg',
          label: '- FFmpeg',
        },
        {
          type: 'doc',
          id: 'video-editing/subtitles-encoding',
          label: '- Subs Encoding',
        },
      ],
    },
  ],
};

export default sidebars;
